apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: petshop-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
   - http:
      paths: 
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-products-service
          servicePort: {{ .Values.products.service.port }}
      - path: /orders
        backend:
          serviceName: {{ .Release.Name }}-orders-service
          servicePort: {{ .Values.orders.service.port }}